apiVersion: v1
kind: Service
metadata:
  name: upstage-gangwon-backend
  namespace: upstage-gangwon
  labels:
    app: upstage-gangwon-backend
spec:
  type: ClusterIP
  selector:
    app: upstage-gangwon-backend
  ports:
    - name: http
      port: 80
      targetPort: 8800
